/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Pngquant */

#ifndef _Included_Pngquant
#define _Included_Pngquant
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Pngquant
 * Method:    compress
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Pngquant_compress
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     Pngquant
 * Method:    verbose
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_Pngquant_verbose
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     Pngquant
 * Method:    force
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_Pngquant_force
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     Pngquant
 * Method:    quality
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Pngquant_quality
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
